[package]
name = "lidar_viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = "7.1.1"
bevy = { version = "0.9.0", features = ["dynamic"] }
bytemuck = "1.12.3"
bevy_egui = "0.17.1"
rand = "0.8.5"
futures-lite = "1.12.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_parser"
harness = false

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3
