[package]
name = "lidar_viewer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = {version = "1.0.147", features = ["derive"]}
nom = "7.1.1"
byteorder = "1.4.3"


[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "bench_parser"
harness = false